# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enterprise_type', models.SmallIntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('online_status', models.SmallIntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=64)),
                ('system_source', models.SmallIntegerField(blank=True, null=True)),
                ('user_type', models.SmallIntegerField(blank=True, null=True)),
                ('account', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('id_card', models.CharField(blank=True, max_length=20, null=True)),
                ('id_card_back_pic', models.CharField(blank=True, max_length=256, null=True)),
                ('id_card_hand_pic', models.CharField(blank=True, max_length=256, null=True)),
                ('id_card_pic', models.CharField(blank=True, max_length=256, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('opt_id', models.BigIntegerField(blank=True, null=True)),
                ('opt_remark', models.CharField(blank=True, max_length=256, null=True)),
                ('opt_time', models.DateTimeField(blank=True, null=True)),
                ('pay_gestures', models.CharField(blank=True, max_length=64, null=True)),
                ('pay_password', models.CharField(blank=True, max_length=64, null=True)),
                ('real_name', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.SmallIntegerField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('new_time', models.DateTimeField(blank=True, null=True)),
                ('next_level', models.IntegerField()),
                ('user_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'user_level',
            },
        ),
        migrations.CreateModel(
            name='Area_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=250)),
                ('num', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.CharField(max_length=250)),
                ('parentid', models.CharField(max_length=250)),
                ('shortname', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CoinInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_num', models.IntegerField(default=0)),
                ('intergral_num', models.FloatField(default=0.0)),
                ('user_id', models.IntegerField(default=0)),
                ('user_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=250)),
                ('feature', models.CharField(max_length=250)),
                ('pic_file', models.FileField(upload_to='file_upgrade')),
                ('opt_time', models.DateTimeField(auto_now_add=True)),
                ('upload_user_id', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Register_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('pay_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='solve_task_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_id', models.IntegerField(default=0)),
                ('get_task_num', models.IntegerField(default=0)),
                ('solve_task_num', models.IntegerField(default=0)),
                ('solve_user_id', models.IntegerField(default=0)),
                ('opt_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('total_task_num', models.IntegerField(default=0)),
                ('avali_task_num', models.IntegerField(default=0)),
                ('opt_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_type', models.IntegerField(default=0)),
                ('balance', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('opt_record', models.CharField(max_length=50)),
                ('opt_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
