# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0002_auto_20171010_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(max_length=32)),
                ('bank_name', models.CharField(max_length=32)),
                ('bank_account', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('user_id', models.BigIntegerField()),
                ('id_card', models.CharField(max_length=32)),
                ('bank_mobile', models.CharField(max_length=32)),
                ('real_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BankList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='weichat',
            new_name='wechat',
        ),
    ]
