# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0004_solve_task_user_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='opt_time',
            field=models.CharField(max_length=50),
        ),
    ]
